### ISSUE TITLE
Only 1 of each Parameter Type Allowed?

### ISSUE THREAD

**Issue by ErikOmberg** [dnauck/angular-advanced-searchbox#6]
Is only 1 of each parameter type allowed intentional or something that can be fixed up?

As seen in the screen shot, if I add 3 Name parameters, then only 1 Name parameter is in the Output json. Thank you.

![image](https://cloud.githubusercontent.com/assets/8632110/6948784/b0179e1a-d875-11e4-86ef-a163beef999f.png)

**Comment by dnauck** [comment]
Hi,

my use case was to only allow one param. And version 1.1.x has no implementation to enforce this.

What is your use case? What is your expected result?

**Comment by ErikOmberg** [comment]
Use case:
As a user, I want to give multiple email addresses as inputs and return search results on them "logically OR'd".
As a user, I want to be able to add and/or remove one email address at a time from the search parameters to tune my search results.

Having something like this as the searchParams output JSON would be great:
{"query":"whatever query string here", "emailAddress":["e@mail.com", "bill@ms.com"], "name":["Paul", "Mike", "Bill"]}

When the user clicks the "Deleted parameter" trash can icon, then the particular parameter would be removed from the arrays too.

Side note:
I have an MVC.Net server. The json arrays would get converted in to a collection and then used to setup the search parameters passed to the index (ElasticSearch).

**Comment by dnauck** [comment]
I added the enforcement of only on search param of the same key in 35f051e

This was the default behavior.

Now we should think about how we can archive your suggestion:

* How should the user know if multiple parameters are OR'ed or AND'ed ?
* Maybe adding multiple values to one parameter is the solution, but same here .. OR or AND ?

**Comment by ErikOmberg** [comment]
The "enforcement of only on search param of the same key" changes are very nice. I like how it removes the option from the Parameter Suggestions available. That's great. Thank you.

**Comment by elnino1** [comment]
Hi,

I also need to have a list of values for a given key. 

When entered values are long, it's more easier to enter several values instead of using the comma separated value. Which seems to be the actual workaround.

No matter if it's to implement AND or OR, the developer will know what to do with the values. Yes it will be only ORs or only ANDs but you should left the module user deal with it I think.

It would be nice to have an option in parameters to allow value for a key to be an array.

My 2 cents :
A simple solution could be treat all values as arrays and use the option to push or overwrite. Minor changes in isUnsedParameter and updateModel should do the trick I guess.

Regards

**Comment by NealHaggard** [comment]
It would be nice if you could specify if multiple options are allowed are not for a parameter.  So like 'Country' you could say multiple: true and it would allow the user to provide multiple countries in the list, and it would provide them in an array:

{
   country: [ 'United States', 'Canada']
}

**Comment by dnauck** [comment]
Please test the latest build
